{% set name = "scour" %}
{% set version = "0.37" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 963113779c6877cbdd99bb6ea30ac0576dbe8b4156459ac62e579f8d22726116

build:
  noarch: python
  number: 1
  entry_points:
    - scour = scour.scour:run
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - six >=1.9.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - scour.scour
  commands:
    - scour -h
    - pip check

about:
  home: https://github.com/scour-project/scour
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Scour SVG Optimizer
  doc_url: https://github.com/scour-project/scour
  dev_url: https://github.com/scour-project/scour

extra:
  recipe-maintainers:
    - njzjz
    - anjos
