{% set name = "scour" %}
{% set version = "0.38.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7ac1beae8610996de7c0eebe1f1d5538792031ec67893b8aa6d0a356719e9b8

build:
  noarch: python
  number: 0
  entry_points:
    - scour = scour.scour:run
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.9.0

test:
  imports:
    - scour.scour
  commands:
    - scour -h

about:
  home: https://github.com/scour-project/scour
  license: Apache-2.0
  license_family: Apache
  summary: Scour SVG Optimizer
  doc_url: https://github.com/scour-project/scour
  dev_url: https://github.com/scour-project/scour

extra:
  recipe-maintainers:
    - njzjz
